/**
 * Base seed: glossary (hy + en), demo accounts for every role, the Armenian
 * grid emission factor, and the bilingual contract template.
 * Idempotent — running twice does not duplicate.
 */
import postgres from "postgres";
import { hash } from "bcryptjs";
import { seedGlossaryEntries } from "@/lib/glossary/content";

async function main() {
  const url = process.env.DATABASE_ADMIN_URL ?? process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL must be set");
  const sql = postgres(url, { max: 1, prepare: false });

  // ---------------- glossary
  for (const e of seedGlossaryEntries()) {
    await sql`
      insert into glossary_entry (key, locale, term, short, eli5, why_it_matters, example, group_key, related_keys)
      values (${e.key}, ${e.locale}, ${e.term}, ${e.short}, ${e.eli5}, ${e.whyItMatters},
              ${e.example}, ${e.groupKey}, ${JSON.stringify(e.relatedKeys)}::jsonb)
      on conflict (key, locale) do update
        set term = excluded.term, short = excluded.short, eli5 = excluded.eli5,
            why_it_matters = excluded.why_it_matters, example = excluded.example,
            group_key = excluded.group_key, related_keys = excluded.related_keys
    `;
  }
  console.log("glossary seeded (hy + en)");

  // ---------------- emission factor (S8-1)
  // Armenia combined margin 0.436 tCO₂eq/MWh. Stored as versioned dated data;
  // this seed is the ONLY place the number may appear in code.
  const existing = await sql`select id from emission_factor where grid_region = 'AM' and version = 1`;
  if (existing.length === 0) {
    await sql`
      insert into emission_factor (grid_region, cm_tco2_per_mwh, om_tco2_per_mwh, bm_tco2_per_mwh,
                                   om_weight, bm_weight, source_reference, version, valid_from)
      values ('AM', 0.436, 0.512, 0.284, 0.67, 0.33,
              'Armenia grid CM factor — national CDM baseline study (seed reference; replace with the dated official source document in the vault)',
              1, '2024-01-01T00:00:00Z')
    `;
    console.log("emission factor seeded: AM 0.436 tCO2e/MWh (v1)");
  }

  // ---------------- demo users, one per role
  // Password defaults to "portal-demo"; set DEMO_PASSWORD to override.
  // When DEMO_PASSWORD is explicitly set, existing demo accounts are updated
  // to it — so rotating the password is one env var + one deploy.
  const demo: Array<[string, string, string]> = [
    ["admin@portal.am", "Admin", "admin"],
    ["ops@portal.am", "Operations", "ops"],
    ["mrv@portal.am", "MRV Analyst", "mrv_analyst"],
    ["carbon@portal.am", "Carbon Manager", "carbon_manager"],
    ["commercial@portal.am", "Commercial", "commercial"],
    ["tech@portal.am", "Field Tech", "field_tech"],
    ["owner@portal.am", "Demo Owner", "owner"],
    ["vendor@portal.am", "Demo Vendor", "vendor"],
    ["auditor@portal.am", "Demo Auditor", "auditor"],
  ];
  const explicitPassword = process.env.DEMO_PASSWORD;
  const pw = await hash(explicitPassword ?? "portal-demo", 12);
  for (const [email, name, role] of demo) {
    if (explicitPassword) {
      await sql`
        insert into app_account (email, password_hash, name, role)
        values (${email}, ${pw}, ${name}, ${role}::user_role)
        on conflict (email) do update set password_hash = excluded.password_hash
      `;
    } else {
      await sql`
        insert into app_account (email, password_hash, name, role)
        values (${email}, ${pw}, ${name}, ${role}::user_role)
        on conflict (email) do nothing
      `;
    }
  }
  console.log(
    `demo accounts seeded (password: ${explicitPassword ? "from DEMO_PASSWORD" : "portal-demo"})`,
  );

  // ---------------- contract template v1, both locales (S2-1/S2-2)
  for (const [locale, body] of [
    [
      "en",
      `ATTRIBUTE TRANSFER AGREEMENT (v1)

1. WHAT YOU ARE TRANSFERRING. You transfer to the Registrant the environmental attributes of the electricity generated by the Site, except the Retained Share of {{retained_share_pct}}%.
2. WHAT YOU ARE PAID. {{payment_basis}}: {{rate}}. Payments follow each reconciled period.
3. NO DOUBLE COUNTING (acknowledged separately). You will not claim, sell or report the transferred attributes elsewhere. You may still claim your Retained Share.
4. WHAT YOU MAY STILL SAY. "Our site hosts solar generation" — yes. "We run on the solar power we sell attributes for" — no.
5. TERM. {{term_months}} months, {{notice_period_days}} days notice.`,
    ],
    [
      "hy",
      `ԱՏՐԻԲՈՒՏՆԵՐԻ ՓՈԽԱՆՑՄԱՆ ՊԱՅՄԱՆԱԳԻՐ (v1)

1. ԻՆՉ ԵՔ ՓՈԽԱՆՑՈՒՄ: Դուք Գրանցողին եք փոխանցում Կայանի արտադրած էլեկտրաէներգիայի բնապահպանական ատրիբուտները, բացառությամբ {{retained_share_pct}}% Պահվող բաժնի:
2. ԻՆՉ ԵՔ ՍՏԱՆՈՒՄ: {{payment_basis}}: {{rate}}: Վճարումները կատարվում են ամեն համադրված ժամանակաշրջանից հետո:
3. ԿՐԿՆԱԿԻ ՀԱՇՎԱՌՈՒՄ ՉԿԱ (հաստատվում է առանձին): Դուք չեք հայտարարի, վաճառի կամ հաշվետվության մեջ չեք ներառի փոխանցված ատրիբուտները այլ տեղ: Պահվող բաժինը մնում է ձերը:
4. ԻՆՉ ԿԱՐՈՂ ԵՔ ԴԵՌ ԱՍԵԼ: «Մեր կայանում արևային արտադրություն կա» — այո: «Մենք աշխատում ենք այն արևային էներգիայով, որի ատրիբուտները վաճառում ենք» — ոչ:
5. ԺԱՄԿԵՏ: {{term_months}} ամիս, {{notice_period_days}} օր ծանուցում:`,
    ],
  ] as const) {
    await sql`
      insert into contract_template (code, version, locale, body, effective_from)
      values ('OWNER_ATTRIBUTE_TRANSFER', 1, ${locale}, ${body}, '2026-01-01T00:00:00Z')
      on conflict on constraint template_code_version_locale do nothing
    `;
  }
  console.log("contract template v1 seeded (hy + en)");

  await sql.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
